# WHU+P2V

out_dir: p2v
criterion: WBCE
model: P2V
out_type: logits

p2v_model:
  in_ch: 3
  video_len: 8
cmb_coeffs:
  - 1.0
  - 0.4


device: cuda:0

# Optimizer
optimizer: Adam
lr: 0.001
weight_decay: 0.0
load_optim: False
save_optim: False
sched_on: True
schedulers:
  - name: StepLR
    step_size: 25
    gamma: 0.2

repeats: 6
batch_size: 8