# WHU+P2V

out_dir: clnet
criterion: WBCE
weights: 
  - 0.5   # Weight of no-change class
  - 0.5   # Weight of change class
model: CLNet
out_type: logits

p2v_model:
  in_ch: 3
  video_len: 8
cmb_coeffs:       
  - 1.0
  - 0.4
  - 0.4


device: cuda:2
